update

diff --git a/.github/workflows/if-with-function.yaml b/.github/workflows/if-with-function.yaml
--- a/.github/workflows/if-with-function.yaml
+++ b/.github/workflows/if-with-function.yaml
@@ -8,10 +8,12 @@ on:
 jobs:
     quality-check:
         runs-on: ubuntu-latest
-        if: startsWith(github.ref_name,'main') && github.event_name == 'push'
+        if: startsWith(github.ref_name,'feature') && github.event_name == 'push'
         steps:
             - name: perform code quality
-              run: echo "performing quality checks on the code "
+              run: |
+                echo "performing quality checks on the code " 
+                exit 1  #for failure function test
     dev-deploy:
         runs-on: ubuntu-latest
         if: startsWith(github.ref_name,'develop') && github.event_name == 'push'
@@ -24,29 +26,21 @@ jobs:
         steps:
             - name: perform code quality
               run: echo "deploying the code to ${{github.ref_name}}" 
-    successful-notification:
+    notification:
         runs-on: ubuntu-latest
-        if: always() && !failure()
+        if: always() 
         needs:
             - quality-check
             - dev-deploy
             - prod-deploy
         steps:
+            - name:  failed notification
+              if: failure()
+              run: echo "email is  failed to send"
             - name: successfull notification
-           
+              if: success()
               run: echo "email is working" 
            
-    failed-notification:
-        runs-on: ubuntu-latest
-        if: failure()
-        needs:
-            - quality-check
-            - dev-deploy
-            - prod-deploy
-        steps:
-          
-            - name:  failed notification
-          
-              run: echo "email is  failed to send"
+    
 
     
